[package]
name = "learn-tower"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.43"
tokio = { version = "1.11.0", features = ["full"] }
tower = { version = "0.4.8", features = ["full"] }
