[package]
name = "learn-hyper"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3.17"
hyper = { version = "0.14.12", features = ["full"] }
tokio = { version = "1.11.0", features = ["full"] }
